# Iniciar o .venv
venv:
	. ../.venv/bin/activate
.PHONY: venv

# # Instalar dependências
# install:
# 	source ../.venv/bin/activate
# 	pip install -r requirements.txt
# .PHONY: install

.SILENT: # this has no purpose but to prevent echoing of commands for all targets